// <auto-generated />
namespace Cars.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class logupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(logupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201907162113415_logupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
